-- CreateEnum
CREATE TYPE "AuditEvent" AS ENUM ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'ACCOUNT_LOCKED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_SUCCESS', 'PASSWORD_CHANGED', 'LOGOUT', 'LOGOUT_ALL', 'REFRESH_TOKEN_REUSE_DETECTED', 'ADMIN_FORCE_RESET');
