import type { Product } from "./types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Laptop Gaming",
    category: "Electronics",
    price: 15000000,
    stock: 12,
    description: "High performance gaming laptop",
    size: ["S", "M", "L", "XL"],
  },
  {
    id: "2",
    name: "Wireless Mouse",
    category: "Accessories",
    price: 250000,
    stock: 45,
    description: "Ergonomic wireless mouse",
    size: ["S", "M", "L"],
  },
  {
    id: "3",
    name: "Mechanical Keyboard",
    category: "Accessories",
    price: 850000,
    stock: 28,
    description: "RGB mechanical keyboard",
    size: ["M", "L", "XL"],
  },
  {
    id: "4",
    name: 'Monitor 27"',
    category: "Electronics",
    price: 3500000,
    stock: 15,
    description: "4K UHD monitor",
    size: ["L", "XL"],
  },
  {
    id: "5",
    name: 'Monitor 27"',
    category: "Electronics",
    price: 3500000,
    stock: 15,
    description: "4K UHD monitor",
    size: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "6",
    name: 'Monitor 20"',
    category: "Electronics",
    price: 3500000,
    stock: 0,
    description: "4K UHD monitor",
    size: ["M", "L"],
  },
];
